services:
  Heimseiten\ContaoColumnsBundle\Listener\HooksListener:
    tags:
      - { name: contao.hook, hook: getContentElement, method: onGetContentElement, priority: 0 }
      - { name: contao.hook, hook: parseTemplate, method: onParseTemplate, priority: 0 }
